### ISSUE TITLE
Task tracking.

### ISSUE THREAD

**Issue by ClaasStoertenbecker** [roxlukas/lmeve#32] opened 2016-05-26 15:22 UTC
It seems like that the tool is not tracking the tasks of all members correctly.
Could you explain the mechanic how the tool checks task progress ?
I think it is most likely a humanerror of mine and or corporation members.

cheers Claas Stoertenbecker

**Comment by roxlukas** [comment] 2016-05-26 18:17
Tasks are specific industry action (manufacturing, invention, copying, research, etc) of specific item assigned to a specific character. They help coordinating big industry operation when you want to divide tasks between multiple members. Administrator assigns tasks with specific quantities, so corp does not overproduce intermediate products such as blueprint copies for invention or advanced mats.

Tasks are tracked over a month long cycle, starting on 1st of a month until the last day of month.

Tasks are normally recurring every month (starting at 0% completion), but they can be set as "one time". Such tasks will only appear in the month they were assigned, and will not appear in the following months.

Tasks can be assigned by a person with "Edit Tasks" right (by default Administrator and Officer roles have this right).

Tasks can only be completed by the character they were assigned to. Even if a player has multiple alts, work done by alts wont count toward task completion. Each character has their own tasks.

LMeve can and will track all industry actions done by corp members, but they will be under a) statistics b) character page and not under Tasks. Tasks are reserved for activities ordered by the corp to its members.

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 10:06
So the progress of a task is calculated with the help of industry jobs done by the character that the task was assigned to ? So the progress of a task should updated every 15minutes after the api poll right ?

**Comment by roxlukas** [comment] 2016-05-27 10:18
Yes, progress bars are updated based on data from IndustryJobs and IndustryJobsHistory API endpoints.

IndustryJobs updates every 15 minutes, and IndustryJobsHistory updates every 6 hours. You can double check that IndustryJobs and IndustryJobsHistory get updated under Statistics -> EVE API Statistics.

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 10:28
http://imgur.com/a/XA1de this is what makes me wonder.

**Comment by roxlukas** [comment] 2016-05-27 10:52
According to the blitz icon this is a "one time task". Such tasks are
counted since task creation:  beginProductionTime > taskCreateTimestamp

If you change it to recurring task, progress under tasks will change from
50 to 100 (whole month will be counted instead of since task creation

2016-05-27 12:28 GMT+02:00 ClaasStoertenbecker <notifications@github.com>:

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 10:56
I know how onetime tasks work but the point is that all autocannons where produced after the task was created. So it should work properly or am i wrong ?

**Comment by roxlukas** [comment] 2016-05-27 11:34
Ok let's debug this. We will need output of the two queries below. You
might want to send the results directly to my mail rather than share
publicly.

SELECT * FROM `lmtasks` WHERE `characterID`=[characterID];

SELECT * FROM `apiindustryjobs` WHERE `installerID`=[characterID];


2016-05-27 12:56 GMT+02:00 ClaasStoertenbecker <notifications@github.com>:

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 11:46
Ok ive found that the jobs apiindustryjobs wise where installed before taskcreation. But first i know that they where 100% installed after task creation and second it is a bit strange that there is a nearly perfect 2hour difference between the timestamps. Probably there is another bug.
P.s currently the tool runs on exact eve time.

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 11:50
Ok i checked the two tables and found out that the jobs where created before taskcreation but im not sure how that could happen. I will observe it and tell you if i encounter this phenomenon a second time.

**Comment by roxlukas** [comment] 2016-05-27 11:57
I think I know what the issue is timezone mismatch. Tasks are in local time, whereas data from API is in UTC

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 11:59
Exactly.

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 14:09
Noticed another strange thing. The time that shows up above in the tool is actually UTC but it is not used for the jobcreation stuff.

**Comment by roxlukas** [comment] 2016-05-27 14:46
That's because it's explicitly defined as UTC (it's supppsed to show EVE time). I will do the same everywhere else where timestamps are used.

**Comment by roxlukas** [comment] 2016-05-30 15:08
Included in the upcoming patch

**Comment by roxlukas** [comment] 2016-06-01 05:22
Fixed in d132dd5

**Closed by roxlukas** 2016-06-01 05:22 UTC
Labels: bug
