### ISSUE TITLE
Assets mapping to wrong Stations

### ISSUE THREAD

**Issue by ClaasStoertenbecker** [roxlukas/lmeve#27] opened 2016-05-16 13:54 UTC
Hello,

For me LMEVE is mapping the Assets to a wrong Station. The Assets are fine but located under the wrong Station. Also is SOV calculated in Fuelblockconsumption ?

**Comment by roxlukas** [comment] 2016-05-17 07:25
Thanks for your bug report.

To investigate I would need the asset data from your instance (raw xml from
api cache under lmeve/var/ and apiassets table from mysql so I can compare
them and verify if the api poller loads the data correctly to db). Are you
willing to share this information?

Fuelblock consumption doesn't take into account TCU bonus. It is however
rather simple feature to add, so I've added it to the ToDo list.

**Comment by ClaasStoertenbecker** [comment] 2016-05-17 14:09
Because your tool is so amazing im surely willing to provide you the information you need to fix the bug. Just tell me on what platform you want me to send it to you because i dont want it to share that openly.

Btw. can i somehow contact you on a easier way ? GitHub sure is great for bug reports but since your tool isnt that well documented it is quite hard to get into it for new users (besides the installation, it is well documented if you know how2linux).

cheers Claas Störtenbecker

**Comment by roxlukas** [comment] 2016-05-17 15:18
Please send it to my e-mail at pozniak(dot)lukasz(at)gmail(dot)com

Thanks!

2016-05-17 16:09 GMT+02:00 ClaasStoertenbecker <notifications@github.com>:

**Comment by ClaasStoertenbecker** [comment] 2016-05-17 15:52
Done

**Comment by ClaasStoertenbecker** [comment] 2016-05-24 15:18
Have you got my E-Mail? Im just curious because there wasnt any reply.

**Comment by roxlukas** [comment] 2016-05-24 15:21
I did yes, but been very busy and didnt look into it yet.

I'll get back to you as soon as I find the cause

Best regards,
Łukasz Poźniak

**Comment by ClaasStoertenbecker** [comment] 2016-05-27 10:46
I checked how lmeve.apiassets is mapped to eve_cit_dbo.staStations and found no problem there. So i think either the API somehow messes up in pulling the right locationID or the eve dump is wrong. The both stations are btw. only 1 digit apart. (60014943 and 60014944).

**Comment by roxlukas** [comment] 2016-05-30 17:01
Bug confirmed. Fix included in the upcoming patch.

**Comment by roxlukas** [comment] 2016-06-01 05:23
Fixed in d132dd5

**Closed by roxlukas** 2016-06-01 05:23 UTC
Labels: bug
