### ISSUE TITLE
Assets Not Being Retrieved

### ISSUE THREAD

**Issue by Wildweasel24** [roxlukas/lmeve#46] opened 2017-01-11 01:58 UTC
Have done a fresh install on Debian of the latest code.

Full corporate api key with no expiry, character is the CEO, access mask 134217727

Corporation based in an engineering complex, with all assets residing there.

Assets XML file not showing any assets, even though there are assets in corporate hangars and those items are marked in the DB with stock level monitoring e.g. trit

All other corp information polled and retrieved ok.  No obvious error messages in poller.txt.

Tested using 2nd existing long time corp with 0.1.57 release, picks up assets in same EC no issue.

assets.xml

<?xml version='1.0' encoding='UTF-8'?>
<eveapi version="2">
  <currentTime>2017-01-11 00:01:16</currentTime>
  <result>
    <rowset name="assets" key="itemID" columns="itemID,locationID,typeID,quantity,flag,singleton" />
  </result>
  <cachedUntil>2017-01-11 05:58:16</cachedUntil>
</eveapi>

Poller.txt
...
<b>11.01.2017 0:01:12 [CLI]:</b> [INFORM] Main: Polling assets, this may take a while...
<br>
<b>11.01.2017 0:01:12 [CLI]:</b> [INFORM] Main: Polling public API feeds...
<br>
<b>11.01.2017 0:01:12 [CLI]:</b> [INFORM] Main: Polling public CREST feeds...
<br>
<b>11.01.2017 0:01:17 [CLI]:</b> [INFORM] Main: Polling eve-central.com feeds...
<br>
<b>11.01.2017 0:01:17 [CLI]:</b> [INFORM] Main: Success! Import took 75.455547809601 seconds.
<br>
...

**Comment by Wildweasel24** [comment] 2017-01-11 10:01
After 3 days of no assets showing, some assets in an NPC station have now appeared, but still nothing from the (public EC) hangars.

**Comment by roxlukas** [comment] 2017-01-12 10:33
Thanks for the report.

I assume **Assets -> Stock** shows correct data, but **Assets -> Inventory** does not. If that's the case, then I guess the culprit is the SQL query in function getInventory(). Asset location name is coalesced from **mapDenormalize** (SDE table which contains all "static" in game locations like systems, stations, planets and moons) and **apiconquerablestationslist** which is LMeve table and holds outposts and conquerable stations retrieved from EVE API.

Now that Citadel was deployed last year, there is no citadel/EC list in LMeve for the items in assets to bind to.

To confirm this is the case, I would need to inspect the following XML files:
- <LMeve base dir>/var/AssetList_<keyID>.xml
- <LMeve base dir>/var/ConquerableStationList.xml
- <LMeve base dir>/var/Facilities_<keyID>.xml
- <LMeve base dir>/var/Locations<keyID>.xml
- <LMeve base dir>/var/StarbaseList_<keyID>.xml

If you choose to send these files to me, please know that I do not intend to disclose this information to anyone, but for your information, these files do contain confidential in-game information and are very useful source of intel.

**Comment by roxlukas** [comment] 2017-01-24 09:33
There's been no update or communication regarding this issue. Does it mean it's solved?

**Comment by Wildweasel24** [comment] 2017-02-04 03:37
Apologies, RL issue kept me offline.

Assets became visible once corp owning the assets also became the EC owner, hence seems to be an issue with asset visibility in corporation hangars in 3rd party owned EC's.

**Comment by roxlukas** [comment] 2017-02-04 14:45
Ok, I think when your corporation became owner of the Engineering Complex, it showed up in Corporation API under Locations Endpoint.

**Comment by subaqua** [comment] 2017-03-04 20:43
I think we are seeing this same issue - most of our corp assets are in EC and Citadels where we rent office space from another organization.    Is there a work-around or anything you think we can try to resolve it?   Thanks!

**Comment by roxlukas** [comment] 2017-03-05 12:27
The problem is not with assets themselves, because they are retrieved
properly from API, but lack of EC and Citadel information in XML API. It
only shows up in Locations.xml if your corporation owns the Citadel.

I'll have to find out if there is public listing of EC/Citadels.

2017-03-04 21:43 GMT+01:00 Aquamo <notifications@github.com>:

**Comment by subaqua** [comment] 2017-03-07 14:40
Is this useful?  https://stop.hammerti.me.uk/api/

**Comment by roxlukas** [comment] 2017-03-08 07:04
It is for now, but I'd prefer to use ESI only (I will be switching from
eve-central.com API to ESI as well)

2017-03-07 15:40 GMT+01:00 Aquamo <notifications@github.com>:

**Comment by Rayvenhaus** [comment] 2017-08-31 01:27
I also as not seeing any assets being pulled from the EC's that I own. One is in HiSec and one is in NullSec. It's been several days now and nothing is appearing.

**Comment by roxlukas** [comment] 2017-08-31 09:03
As far as I can remember Assets in Citadels owned by your corp should work correctly in the latest commit (2be864da24822f9eed8237a6b80d02dd89dceb53)

Are you running the cutting edge version or something older?

**Comment by Rayvenhaus** [comment] 2017-08-31 10:51
I'm not sure, how do I update to the "cutting edge"?

**Comment by roxlukas** [comment] 2017-08-31 11:21
I'd need the details of your deployment to tell you exactly (did you install it yourself? using the prebuilt VM?) but the high level instruction is:

1) go to project main page, click Clone or Download, download as zip
2) unpack the zip file and overwrite your installation with new files

**Comment by roxlukas** [comment] 2018-10-07 19:39
fixed in 9e78c1cf9a4c2e4d0b3e781308471654ab4da627

**Closed by roxlukas** 2018-10-07 19:39 UTC
