### ISSUE TITLE
objects with no market order not showing up in buybacks

### ISSUE THREAD

**Issue by dstevens79** [roxlukas/lmeve#79] opened 2019-01-18 07:01 UTC
seems to happen primarily with ores that are null only, 
 could add an auto +5%/ +10%  to improved ore types off the base ore type if no order found in jita to resolve this in alot of cases

**Comment by roxlukas** [comment] 2019-01-28 13:36
This is by design, but ore values can be calulated using their internal makeup. Closing this issue, will proceed in #80

**Closed by roxlukas** 2019-01-28 13:36 UTC
